---
keys:
  - &adm_hayden age1nmqyc2uapa3zd0gj90484xq56ntcuehjx626e5vqkcenqec3w46qd9xcm4
  - &dev_nixnuc age1wgatar6rw50c5ld0f5dcfq843fgj2tgvaf5nwhzv0cnsj4ad432q7xr9lq
  - &dev_workmac age1k4q7cekyzyadkv3h90z9tjf8pyk7qlxwh07h2u8r6wn0zl0rk34qa3jp9d
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *adm_hayden
          - *dev_nixnuc
          - *dev_workmac
  - path_regex: hosts/phoebe/secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *adm_hayden
          - *dev_nixnuc
