---
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - config/**
      - flake.nix
      - flake.lock

jobs:
  cache:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        configuration:
          - phoebe
          - titan
    steps:
      - uses: easimon/maximize-build-space@v10
        name: Maximize build space
        with:
          overprovision-lvm: true
          remove-android: true
          remove-dotnet: true
          remove-haskell: true
          remove-codeql: true

      - uses: actions/checkout@v4
        name: Checkout

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Setup my cache
        uses: ryanccn/attic-action@v0.2.1
        with:
          endpoint: https://cache.hayden.moe/
          cache: hayden
          token: ${{ secrets.ATTIC_TOKEN }}

      - name: Setup Cachix
        uses: cachix/cachix-action@v15
        with:
          name: nix-community
          extraPullNames: numtime

      - name: Validate flakes
        run: nix flake check

      - name: Build neovim with defaults
        run: nix build .#nixosConfigurations.${{ inputs.configuration }}.config.system.build.toplevel --print-build-logs
